name: shopping_app
description: "A new Flutter project."

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0-107.0.dev <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Remote Database
  supabase_flutter: ^2.5.6

  # Local Database
  shared_preferences: ^2.3.2

  # State management
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  get_it: ^8.0.2

  # Routing
  go_router: ^14.3.0

  # utils
  flutter_screenutil: ^5.9.3
  url_launcher: ^6.3.1
  permission_handler: ^11.3.1
  network_info_plus: ^6.0.2
  fluttertoast: ^8.2.8
  geolocator: ^13.0.1
  connectivity_plus: ^6.0.5
  intl: ^0.20.1
  flutter_svg: ^2.0.10+1
  flutter_otp_text_field: ^1.2.0
  rename: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    # Image Asset
    - assets/images/auth/
    - assets/images/splash/

    # API key
    - assets/supa_base_key/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
